apiVersion: v1
kind: Pod
metadata:
  name: kuard-config-secret
spec:
  containers:
    - name: test-container
      image: gcr.io/kuar-demo/kuard-amd64:1
      imagePullPolicy: Always
      command:
        - "/kuard"
        - "$(EXTRA_PARAM)"
      env:
        - name: EXTRA_PARAM
          valueFrom:
            configMapKeyRef:
              name: my-config
              key: extra-param
      volumeMounts:
        - name: config-volume
          mountPath: /config
        - name: tls-certs
          mountPath: /tls
          readOnly: true
  volumes:
    - name: config-volume
      configMap:
        name: my-config
    - name: tls-certs
      secret:
        secretName: kuard-tls
  restartPolicy: Never