apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: nginx
spec:
  replicas: 3
  minReadySeconds: 2
  selector:
    matchLabels:
      app: nginx
  # set up readiness checks so
  # rollouts work as expected
  strategy:
    rollingUpdate:  
      maxSurge: 25%
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      annotations:
        kubernetes.io/change-cause: "Back to Nginx 1.19.6 again"
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:1.19.6
        # image: nginx:1.18.0
        ports:
        - containerPort: 80